Feature/autocomplite
artbear/gherkin-autocomplete pull request #1
Opened 2018-10-01 15:38 UTC by pumbaEO

Обновление vscode, доработка работы с мульти папками в рабочей области и обновлении кєша. Включил обработку ссілки на Export scenarios

2018-10-02 09:44 UTC, pumbaEO commented
@artbear  ping

2018-10-02 10:55 UTC, artbear commented
@pumbaEO Вечером посмотрю, пока рабочие задачи решаю.

2018-10-03 05:51 UTC, artbear commented
@pumbaEO У меня выдается ошибка

```
src/global.ts:155:43 - error TS2339: Property 'getWorkspaceFolder' does not exist on type 'typeof workspace'.

155         let rootFolder = vscode.workspace.getWorkspaceFolder(filename);
```

npm install я сделал до этого

2018-10-03 05:54 UTC, artbear commented
И еще у меня постоянно выдается ошибка
PS W:\repo\SB\gherkin-autocomplete> tsc -p ./
error TS5023: Unknown compiler option 'importHelpers'.
PS W:\repo\SB\gherkin-autocomplete> tsc
error TS5023: Unknown compiler option 'importHelpers'.

@pumbaEO @nixel2007 как лечить?

2018-10-03 06:45 UTC, nixel2007 commented
Typescript какой версии?

2018-10-03 06:52 UTC, pumbaEO commented
1. удали папку node_modules, и сделай заново npm install 
2. Ты же сам обновил до typescript 3, обнови у себя и глобально.  https://github.com/artbear/gherkin-autocomplete/commit/da71a8bf4b9de69ab066f0c802328c3078e1c374#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R77

2018-10-03 07:27 UTC, pumbaEO commented
> @pumbaEO У меня выдается ошибка
> 
> ```
> src/global.ts:155:43 - error TS2339: Property 'getWorkspaceFolder' does not exist on type 'typeof workspace'.
> 
> 155         let rootFolder = vscode.workspace.getWorkspaceFolder(filename);
> ```
> 
> npm install я сделал до этого

https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

2018-10-03 07:46 UTC, artbear commented
@pumbaEO А зачем закрыл? будешь переделывать?

2018-10-03 07:47 UTC, pumbaEO commented
Нет случайно.

2018-10-03 09:06 UTC, artbear requested changes
В целом у меня собралось и заработало.

Но нужны небольшие доработки.

2018-10-03 09:06 UTC, artbear commented on package.json
> +        "lokijs": "^1.5.0",
@pumbaEO точно нужно понизить версию?
на `"lokijs": "^1.5.0"` ?

2018-10-03 09:06 UTC, artbear commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
@pumbaEO А есть смысл в этом
- сначала выше убирать `const wordRange: vscode.Range`
- а затем делать приведение??
`new vscode.Range((wordRange as vscode.Range).start, position)`

раньше было
```javascript
const wordRange: vscode.Range
new vscode.Range(wordRange.start, position)
```

зачем лишнее явное приведение?

2018-10-03 09:06 UTC, artbear commented on src/global.ts
> +        // const rootPath = vscode.workspace.workspaceFolders[0].uri.fsPath;
закомментированный код

2018-10-03 09:06 UTC, artbear commented on src/global.ts
>                  result = word + "." + document.getText(document.getWordRangeAtPosition(newRange.start));
document.getWordRangeAtPosition(newRange.start) вроде бы все-таки может вернуть null :(
предлагаю добавить проверку на null
как уже сделано для других случаев использования getWordRangeAtPosition

2018-10-03 09:32 UTC, pumbaEO commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
Там после проверки, чтоб автокоплит сработал wordRange == null ? ""

2018-10-03 10:42 UTC, artbear commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
и что ?
приведение-то зачем делать, если можно тип при инициализации указать?

2018-10-03 11:04 UTC, pumbaEO commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
потому что const надо сразу присваивать, просто определить тип с помощью const и потом присвоить значение - не пройдет. Поэтом проверка на null и потом уже приведение типа, если не null.

2018-10-03 11:31 UTC, nixel2007 commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
а let?

2018-10-03 11:31 UTC, artbear commented on src/global.ts
>                  result = word + "." + document.getText(document.getWordRangeAtPosition(newRange.start));
@pumbaEO Вот это не исправлено
>document.getWordRangeAtPosition(newRange.start) вроде бы все-таки может вернуть null :(
предлагаю добавить проверку на null
как уже сделано для других случаев использования getWordRangeAtPosition

2018-10-03 11:31 UTC, artbear commented
@pumbaEO Вот это не исправлено
>document.getWordRangeAtPosition(newRange.start) вроде бы все-таки может вернуть null :(
предлагаю добавить проверку на null
как уже сделано для других случаев использования getWordRangeAtPosition

2018-10-03 11:33 UTC, artbear commented
Ага, понял, ты ненужный метод, в котором и был код без null, удалил :)

2018-10-03 11:35 UTC, artbear commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
Я вот честно не понял, чем мой код был плох?
```javascript
            const wordRange: vscode.Range = document.getWordRangeAtPosition(position);
            const wordcomplite: string = wordRange == null ? "" :
                document.getText(
                    new vscode.Range(wordRange.start, position));
```
и с точки зрения языка, и по коду читабельно, не?

разве что null можно получить вместо нужного типа.
но это и в Java по умолчанию так, и других языках.

2018-10-03 11:39 UTC, artbear commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
у меня только этот вопрос остался и можно мержить.
если хотите, оставим так.

@pumbaEO @nixel2007 что скажете?

2018-10-03 11:39 UTC, pumbaEO commented on src/features/completionItemProvider.ts
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
![default](https://user-images.githubusercontent.com/166003/46408249-2d6d1200-c71a-11e8-8563-abec1e7d00a9.png)

2018-10-03 12:23 UTC, nixel2007 commented
const wordRange : vscode.Range | undefined = ... ?

ср, 3 окт. 2018 г. в 14:39, Evhen Sosna <notifications@github.com>:

> *@pumbaEO* commented on this pull request.
> ------------------------------
>
> In src/features/completionItemProvider.ts
> <https://github.com/artbear/gherkin-autocomplete/pull/1#discussion_r222276426>
> :
>
> >              const wordcomplite: string = wordRange == null ? "" :
>                  document.getText(
> -                    new vscode.Range(wordRange.start, position)
> +                    new vscode.Range((wordRange as vscode.Range).start, position)
>
> [image: default]
> <https://user-images.githubusercontent.com/166003/46408249-2d6d1200-c71a-11e8-8563-abec1e7d00a9.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/artbear/gherkin-autocomplete/pull/1#discussion_r222276426>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABFJKEFAz1rufkW6i1RY4-iZdd4_hWeqks5uhKILgaJpZM4XCVg7>
> .
>

2018-10-03 12:48 UTC, artbear commented
>const wordRange : vscode.Range | undefined = ... ?
👍 

прикольно, не знал про такую возможность TS.

2018-10-03 12:48 UTC, merged